### ISSUE TITLE
Deeplinks does not work on mobile

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot-mobile-app#275] opened 2021-01-31 06:20 UTC
If I shared a Chatwoot link (eg: `https://app.chatwoot.com/accounts/<account-id>/conversations/<converstion-id>`) in Telegram/Whatsapp, clicking on the link does not open the app instead it would open the mobile browser.

**Comment by muhsin-k** [comment] 2021-02-02 06:03
Closing this as it is a duplicate of #141

**Closed by muhsin-k** 2021-02-02 06:03 UTC
Labels: bug, ios
