### ISSUE TITLE
Send push notifications are not working on the Mobile App

### ISSUE THREAD

**Issue by Edik-Apoyan** [chatwoot/chatwoot-mobile-app#710] opened 2023-06-21 13:19 UTC
### Describe the bug

When the user is enabled "Send push notifications" on Mobile App the user doesn’t get any notifications 

### To Reproduce

1. Open Mobile App
2. Make sure "Send push notifications" are enabled
3. Close the App without logout 
4. Navigate to the webpage and send a message

### Expected behavior

Send push notifications should work properly

### Environment

app.chatwoot.com

### Cloud Provider

None

### Platform

Mobile

### Operating system

IOS

**Comment by muhsin-k** [comment] 2023-07-24 06:36
Sorry for the late reply. Are you still facing the issue?

**Comment by zaronwald** [comment] 2023-11-08 01:37
I'd love to take this issue? Can you describe it a little more in depth for me. Are you receiving a message and there is no push notification?

**Comment by zaronwald** [comment] 2023-11-28 01:59
After taking a look at this, it seems like any necessary changes would need to be within the API

**Comment by salomonamiga** [comment] 2024-04-05 21:15
Hello
I have chatwoot on my own server
I have the official mobile app on my iPhone, but, im not getting any notifications
can anyone help me please ?

**Comment by luisfrt** [comment] 2024-04-06 02:31
> Hello I have chatwoot on my own server I have the official mobile app on my iPhone, but, im not getting any notifications can anyone help me please ?

Please see https://www.chatwoot.com/hc/handbook/articles/1687935909-push-notification

You need to define FCM_SERVER_KEY in both your sidekick and chatwoot environment variables in order for it to work.

**Comment by salomonamiga** [comment] 2024-04-10 06:08
I have defined in both sides as:
- ENABLE_PUSH_RELAY_SERVER=true
- FCM_SERVER_KEY=XXXXXX (my Firebase Cloud Messaging Key pair)

but still not getting notifications, am I doing something wrong ?

**Comment by a5r0n** [comment] 2024-04-10 12:10
Try ENABLE_PUSH_RELAY_SERVER=false.
As you setting your own firebase id, you have to disable the relay server

**Comment by salomonamiga** [comment] 2024-04-14 19:07
> Try ENABLE_PUSH_RELAY_SERVER=false. As you setting your own firebase id, you have to disable the relay server

I have done that, but still not getting mobile notifications, any other ideas ?

**Comment by muhsin-k** [comment] 2024-07-15 09:34
@salomonamiga Are you still facing this issue?

**Comment by muhsin-k** [comment] 2024-07-15 09:34
Closing this issue, for now. Please feel free to reopen this if it is still an issue.

**Closed by muhsin-k** 2024-07-15 09:34 UTC

**Comment by salomonamiga** [comment] 2024-07-15 09:44
> @salomonamiga Are you still facing this issue?

yes, the issue is still there !
any help please ?

**Comment by salomonamiga** [comment] 2024-07-15 09:51
yes, tried everything

**Comment by laianeramos** [comment] 2024-10-05 01:57
for me doesn't appear the ENABLE_PUSH_RELAY_SERVER here:

![image](https://github.com/user-attachments/assets/4d159f0d-c82b-47e0-837b-9f45fda96360)

in the .env it should be set as true ou false? @muhsin-k

**Comment by laianeramos** [comment] 2024-10-05 10:56
Worked for me by removing the env variable CHATWOOT_HUB_URL. I set the variable ENABLE_PUSH_RELAY_SERVER=true too.
Now push and sound notifications are working

**Comment by zerowebcorp** [comment] 2025-04-28 01:27
I am receiving push notification but it is not triggering the notification sound on mobile. Thought? Android. Phone is not silent
