### ISSUE TITLE
Add copy button

### ISSUE THREAD

**Issue by TheProcedural** [chatwoot/chatwoot-mobile-app#784] opened 2024-05-21 11:44 UTC
**Is your enhancement request related to a problem? Please describe.**
In the conversation details the attributes (phone, email, etc) don't have a copy button nor a way to copy. This small detail is a huge miss honestly.

**Describe the solution you'd like**
Add a copy button.

**Describe alternatives you've considered**
None, not having a copy button is extremely frustrating.

**Additional context**

![image](https://uploads.linear.app/2847f7b9-2caa-474c-b261-1c9bdc2a5da6/f27df385-a764-4b5f-8067-66617d9f41b4/205c48ce-edbb-4b39-8b38-cf43459b5af6?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzI4NDdmN2I5LTJjYWEtNDc0Yy1iMjYxLTFjOWJkYzJhNWRhNi9mMjdkZjM4NS1hNzY0LTRiNWYtODA2Ny02NjYxN2Q5ZjQxYjQvMjA1YzQ4Y2UtZWRiYi00YjM5LThiMzgtY2Y0MzQ1OWI1YWY2IiwiaWF0IjoxNzE2MzI1MTI5LCJleHAiOjMzMjg2ODg1MTI5fQ.DVdkHcdsmwGbveRgnXGZ1DfsJAxujEfjIj-3mv-9AM0)

**Comment by pranavrajs** [comment] 2024-05-21 20:59
Thanks for the feedback. Moving this to mobile app repo as the issue is related to mobile app not the dashboard. @muhsin @sivin Please take a look.

**Comment by pranavrajs** [comment] 2024-05-21 21:04
Oops! Sorry, the tool got me confused. The issue is already in mobile app repo 🙂

**Comment by rahullli** [comment] 2024-05-27 13:05
Hey @pranavrajs can I work on this feature .

**Closed** 2024-05-30 04:09 UTC
