### ISSUE TITLE
No assignment if web interface is close

### ISSUE THREAD

**Issue by Ghost108** [chatwoot/chatwoot-mobile-app#596] opened 2022-11-09 08:08 UTC
**UPDATE 10.11.2022**
the problem with the offline / online situation was fixed by setting the working ours.
BUT: the assignment doesn't work, like I described it below (case 2)

**UPDATE 09.11.2022**
in the second video the widget jumps to offline (from second 9), although I am online in the ios app.
Yes - this is the real problem.
As you can see, while my ios app is permantly active, the widget switches from offline to online to offline, etc...

https://user-images.githubusercontent.com/17011498/200797208-89846a09-b1df-4dad-8e3d-ece52696234d.mp4
https://user-images.githubusercontent.com/17011498/200797250-9c2965ed-29d2-43ee-89f3-9bc3c869a3f8.mp4

Hi all!

I have found a bug which should be fixed as soon as possible.
Version: Self hosted (docker)

**Case 1**
- I am logged on to the PC as agent (web interface)
- User writes a message via Widget
- Dialogflow responds with a custom payload: `{ "action": "handoff" }`
- User is assigned to me

Result: OK

https://user-images.githubusercontent.com/17011498/200773572-c79975e3-fb2f-45e0-9183-ae2a120d4b6a.mp4

**Case 2**
- I am NOT logged on to the PC as agent (web interface) (only on ios app)
- User writes a message via Widget
- Dialogflow responds with a custom payload: `{ "action": "handoff" }`
- User is NOT assigned to me - no assignment!!

Result: NOT OK

https://user-images.githubusercontent.com/17011498/200774004-758d2bac-c981-456b-bf8d-da55bff77450.mp4

**Comment by Ghost108** [comment] 2022-11-29 14:15
Was this bug fixed with version 1.6.18?

**Comment by muhsin-k** [comment] 2022-11-29 17:49
@Ghost108 No. We are working on it. I will be available in the next release.

**Comment by Ghost108** [comment] 2022-11-29 17:50
Okay thanks for that!

**Comment by aerostovtsev** [comment] 2022-12-20 09:59
@muhsin-k  Hello! I am currently observing a similar problem v2.11.0 (docker) and ios app beta 1.7.9 (204). I understand that the fix will be in the next release. Please tell me the release date with fixes.

**Comment by pranavrajs** [comment] 2022-12-20 19:05
@aerostovtsev You can upgrade to 2.12.0 and disable the option to mark offline automatically. This would ensure that you stay even if you are not using the app/dashboard.

**Comment by Ghost108** [comment] 2022-12-20 19:26
this should be fix the problem?
@muhsin-k said that this is an ios app problem, isn't it?

**Comment by muhsin-k** [comment] 2023-02-28 07:29
The issue is fixed in chatwoot v2.12.0. Please feel free to reopen this if it is still an issue.

**Closed by muhsin-k** 2023-02-28 07:29 UTC
Labels: bug, severity: 3, ready-for-pickup
