### ISSUE TITLE
Allow multi line messages in mobile app

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot-mobile-app#271] opened 2021-01-31 06:12 UTC
As an agent, I cannot write long messages in the mobile app as it supports single-line input only. 

- Allow agents to write long messages. Change input to textarea

**Comment by muhsin-k** [comment] 2021-02-02 06:05
Closing this as it is a duplicate of #244

**Closed by muhsin-k** 2021-02-02 06:05 UTC
Labels: feature
