### ISSUE TITLE
Cannot access notification settings

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot-mobile-app#438] opened 2021-10-11 07:57 UTC
Problem:

I can't access Notification settings from the Android app.  Error screenshot is attached to this mail. 

![Screenshot_20211010-181406_Chatwoot](https://user-images.githubusercontent.com/2246121/136753264-86a664c9-b834-4ca3-b6d6-3e4668fef991.jpg)

**Comment by muhsin-k** [comment] 2023-02-28 07:51
The issue is already fixed. We are closing this issue, for now. Please feel free to reopen this if it is still an issue.

**Closed by muhsin-k** 2023-02-28 07:51 UTC
Labels: investigation
